let words=`Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis provident consequuntur earum qui ad dolor adipisci totam ab! At, odio laboriosam voluptas non ipsam error tenetur minima officiis nisi praesentium doloremque deserunt a temporibus iure? Ipsam dolorem earum amet perferendis reiciendis, voluptas omnis dolorum praesentium harum molestias laborum tempore deserunt doloribus illum? Placeat, sequi tempora. Sit quod sint velit distinctio voluptas fugiat omnis reprehenderit quam nihil quasi magni pariatur maxime, doloribus sequi consectetur ab incidunt aspernatur, veniam rerum porro? Beatae possimus vel pariatur? Delectus odit obcaecati voluptates qui excepturi soluta cum. Repellendus, nihil fugiat. Commodi sint similique ducimus quidem iusto.`
let singleWord=words.split(" ");





 const spanEle=`<span class=word1>Lorem</span>
 <span class=word2>ipsum</span>
 <span class=word3>dolor</span>
 <span class=word4>sit</span>
 <span class=word5>amet</span>
 <span class=word6>consectetur</span>
 <span class=word7>adipisicing</span>
 <span class=word8>elit.</span>
 <span class=word9>Perspiciatis</span>
 <span class=word10>provident</span>
 <span class=word11>consequuntur</span>
 <span class=word12>earum</span>
 <span class=word13>qui</span>
 <span class=word14>ad</span>
 <span class=word15>dolor</span>
 <span class=word16>adipisci</span>
 <span class=word17>totam</span>
 <span class=word18>ab!</span>
 <span class=word19>At,</span>
 <span class=word20>odio</span>
 <span class=word21>laboriosam</span>
 <span class=word22>voluptas</span>
 <span class=word23>non</span>
 <span class=word24>ipsam</span>
 <span class=word25>error</span>
 <span class=word26>tenetur</span>
 <span class=word27>minima</span>
 <span class=word28>officiis</span>
 <span class=word29>nisi</span>
 <span class=word30>praesentium</span>
 <span class=word31>doloremque</span>
 <span class=word32>deserunt</span>
 <span class=word33>a</span>
 <span class=word34>temporibus</span>
 <span class=word35>iure?</span>
 <span class=word36>Ipsam</span>
 <span class=word37>dolorem</span>
 <span class=word38>earum</span>
 <span class=word39>amet</span>
 <span class=word40>perferendis</span>
 <span class=word41>reiciendis,</span>
 <span class=word42>voluptas</span>
 <span class=word43>omnis</span>
 <span class=word44>dolorum</span>
 <span class=word45>praesentium</span>
 <span class=word46>harum</span>
 <span class=word47>molestias</span>
 <span class=word48>laborum</span>
 <span class=word49>tempore</span>
 <span class=word50>deserunt</span>
 <span class=word51>doloribus</span>
 <span class=word52>illum?</span>
 <span class=word53>Placeat,</span>
 <span class=word54>sequi</span>
 <span class=word55>tempora.</span>
 <span class=word56>Sit</span>
 <span class=word57>quod</span>
 <span class=word58>sint</span>
 <span class=word59>velit</span>
 <span class=word60>distinctio</span>
 <span class=word61>voluptas</span>
 <span class=word62>fugiat</span>
 <span class=word63>omnis</span>
 <span class=word64>reprehenderit</span>
 <span class=word65>quam</span>
 <span class=word66>nihil</span>
 <span class=word67>quasi</span>
 <span class=word68>magni</span>
 <span class=word69>pariatur</span>
 <span class=word70>maxime,</span>
 <span class=word71>doloribus</span>
 <span class=word72>sequi</span>
 <span class=word73>consectetur</span>
 <span class=word74>ab</span>
 <span class=word75>incidunt</span>
 <span class=word76>aspernatur,</span>
 <span class=word77>veniam</span>
 <span class=word78>rerum</span>
 <span class=word79>porro?</span>
 <span class=word80>Beatae</span>
 <span class=word81>possimus</span>
 <span class=word82>vel</span>
 <span class=word83>pariatur?</span>
 <span class=word84>Delectus</span>
 <span class=word85>odit</span>
 <span class=word86>obcaecati</span>
 <span class=word87>voluptates</span>
 <span class=word88>qui</span>
 <span class=word89>excepturi</span>
 <span class=word90>soluta</span>
 <span class=word91>cum.</span>
 <span class=word92>Repellendus,</span>
 <span class=word93>nihil</span>
 <span class=word94>fugiat.</span>
 <span class=word95>Commodi</span>
 <span class=word96>sint</span>
 <span class=word97>similique</span>
 <span class=word98>ducimus</span>
 <span class=word99>quidem</span>
 <span class=word100>iusto.</span>
`;

export default spanEle;

